### ISSUE TITLE
ember-router-service-polyfill is not required for Ember 2.16.0-beta.1 and later, please remove from your `package.json`

### ISSUE THREAD

**Issue by samselikoff** [rwjblue/ember-router-service-polyfill#10]
Quick question about this warning:

> WARNING: ember-router-service-polyfill is not required for Ember 2.16.0-beta.1 and later, please remove from your `package.json`.

I have `ember-router-service-polyfill` as a `dependency` of my addon. I get this warning because the addon's version of Ember CLI is after 2.16, but potential consumers won't be.

What's the best way to deal with this warning message?

**Comment by rwjblue** [comment]
I should fix it 😃.

Basically, it should only be printed when this addon is included directly in an app, not an addon.
