### ISSUE TITLE
currentURL is undefined

### ISSUE THREAD

**Issue by Turbo87** [rwjblue/ember-router-service-polyfill#8]
On an app that uses Ember 2.8 `currentURL` is being shown as `undefined`. As it is just an alias for `_router.currentURL` I looked at `router:main` and found this:

![bildschirmfoto 2017-10-04 um 13 17 55](https://user-images.githubusercontent.com/141300/31173104-8a7e5b1c-a906-11e7-9a88-5e74cbf3af15.png)

It looks like `currentURL` does not exist, but something called `currentPath` exists instead. 🤔

**Comment by Turbo87** [comment]
![bildschirmfoto 2017-10-04 um 13 24 09](https://user-images.githubusercontent.com/141300/31173311-5636df0e-a907-11e7-977a-4b421ce30636.png)

I just noticed that there is also a `url` property that seems to hold the correct value.

**Comment by rwjblue** [comment]
Seems like we need another test, and a fallback...

**Comment by Turbo87** [comment]
it looks like https://github.com/rwjblue/ember-router-service-polyfill/blob/f091e9b0a190cd2bbaee91c73297ad503983e7e3/tests/acceptance/transition-to-test.js#L117-L118 is testing the wrong thing. what we should test instead are those properties with the same name on the `router` service.
